### PR TITLE
Added API-key tests

### PR DESCRIPTION
**Pull request by cyanthvibes**
poggiewoggies

Co-authored-by: Frank van den Broek <s1130543@student.hsleiden.nl>

### CODE REVIEW

**Review by JAKeijzer96 — DISMISSED** [review]
woggiepoggies!

**Review by frankvdbroek — APPROVED** [review]
image

**Comment by frankvdbroek** [comment]
@cyanthvibes  
image

**Comment by cyanthvibes** [comment]
LGTM!

**Pull request merged**
